# Generated by Django 5.2.10 on 2026-03-19 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='qualification',
            field=models.TextField(blank=True, help_text='Enter qualifications separated by comma (e.g., BTech, MTech)', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.TextField(blank=True, help_text='Enter skills separated by comma (e.g., Python, Django)', null=True),
        ),
    ]
