# Generated by Django 5.2.10 on 2026-04-04 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_job_description_job_qualification_job_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='qualification',
            field=models.TextField(default='', help_text='Enter qualifications separated by comma (e.g., BTech, MTech)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='skills',
            field=models.TextField(default='', help_text='Enter skills separated by comma (e.g., Python, Django)'),
            preserve_default=False,
        ),
    ]
