# Generated by Django 5.2.10 on 2026-03-11 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assignstudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignstudent',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.batch'),
        ),
        migrations.AddField(
            model_name='admission',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.batch'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='adminapp.assignstudent'),
        ),
        migrations.AddField(
            model_name='batch',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.course'),
        ),
        migrations.AddField(
            model_name='assignstudent',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.course'),
        ),
        migrations.AddField(
            model_name='admission',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.course'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.course'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='admission',
            name='enquiry',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admission', to='adminapp.enquiry'),
        ),
        migrations.AddField(
            model_name='facultyassignment',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.batch'),
        ),
        migrations.AddField(
            model_name='facultyassignment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.course'),
        ),
        migrations.AddField(
            model_name='facultyassignment',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='followup',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='followup',
            name='enquiry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='adminapp.enquiry'),
        ),
        migrations.AddField(
            model_name='leaveallocation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.leavetype'),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.leavetype'),
        ),
        migrations.AddField(
            model_name='leaveallocation',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.leavetype'),
        ),
        migrations.AddField(
            model_name='payment',
            name='admission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='adminapp.admission'),
        ),
        migrations.AddField(
            model_name='salary',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='faculty',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='certificate',
            unique_together={('student',)},
        ),
        migrations.AddConstraint(
            model_name='facultyassignment',
            constraint=models.UniqueConstraint(fields=('faculty', 'course', 'batch'), name='unique_faculty_course_batch_per_faculty'),
        ),
        migrations.AddConstraint(
            model_name='salary',
            constraint=models.UniqueConstraint(fields=('faculty', 'month', 'year'), name='unique_salary_per_month'),
        ),
    ]
