# Generated by Django 5.2.10 on 2026-02-03 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_admission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveapplication',
            name='leave_type',
        ),
        migrations.RemoveField(
            model_name='leaveapplication',
            name='user',
        ),
        migrations.DeleteModel(
            name='LeaveType',
        ),
        migrations.DeleteModel(
            name='LeaveApplication',
        ),
    ]
