# Generated by Django 5.2.10 on 2026-02-04 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_remove_leaveapplication_leave_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='course_id',
            new_name='course',
        ),
    ]
