# Generated by Django 5.2.10 on 2026-02-07 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_facultyassignment_unique_faculty_course_batch'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='facultyassignment',
            name='unique_faculty_course_batch',
        ),
    ]
