# Generated by Django 5.2.10 on 2026-02-07 11:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_remove_facultyassignment_unique_faculty_course_batch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='facultyassignment',
            constraint=models.UniqueConstraint(fields=('faculty', 'course', 'batch'), name='unique_faculty_course_batch_per_faculty'),
        ),
    ]
