# Generated by Django 5.2.10 on 2026-02-12 09:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_alter_assignstudent_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignstudent',
            name='completed_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignstudent',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignstudent',
            name='joined_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
