# Generated by Django 5.2.10 on 2026-02-09 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_rename_course_id_enquiry_course'),
        ('adminapp', '0007_alter_assignstudent_student'),
    ]

    operations = [
    ]
