# Generated by Django 5.2.10 on 2026-02-12 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_merge_20260209_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admission',
            name='fees_paid',
        ),
    ]
