# Generated by Django 5.2.10 on 2026-02-13 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0010_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='faculty',
        ),
    ]
