# Generated by Django 5.2.10 on 2026-02-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0011_remove_batch_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Contacted', 'Contacted'), ('Converted', 'Converted'), ('Not Interested', 'Not Interested'), ('Closed', 'Closed')], default='New', max_length=20),
        ),
    ]
