# Generated by Django 5.2.10 on 2026-02-19 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0014_alter_enquiry_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
