# Generated by Django 5.2.10 on 2026-02-19 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0015_alter_enquiry_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='followup',
            options={'ordering': ['-created_at']},
        ),
    ]
