# Generated by Django 5.2.10 on 2026-02-19 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0016_alter_followup_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='followup',
            options={},
        ),
    ]
