# Generated by Django 5.2.10 on 2026-02-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0017_alter_followup_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='next_followup_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
