# Generated by Django 5.2.10 on 2026-02-22 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0018_enquiry_next_followup_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followup',
            name='remarks',
        ),
        migrations.AddField(
            model_name='followup',
            name='next_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='followup',
            name='today_remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
