# Generated by Django 5.2.10 on 2026-02-23 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0019_remove_followup_remarks_followup_next_remark_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followup',
            name='next_remark',
        ),
    ]
