# Generated by Django 5.2.10 on 2026-02-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0020_remove_followup_next_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='next_followup_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
