# Generated by Django 5.2.10 on 2026-02-07 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_assignstudent'),
        ('faculty', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='batch',
            field=models.ForeignKey(default=181, on_delete=django.db.models.deletion.CASCADE, to='adminapp.batch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='faculty',
            field=models.ForeignKey(default=99, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='approval_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
