# Generated by Django 5.2.10 on 2026-03-11 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapp', '0002_initial'),
        ('faculty', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='facultycoursematerial',
            name='faculty',
            field=models.ForeignKey(limit_choices_to={'role__role_name': 'faculty'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facultydailyreport',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.batch'),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_as_faculty', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_as_student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.batch'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='facultydailyreport',
            unique_together={('faculty', 'report_date', 'start_time')},
        ),
        migrations.AddConstraint(
            model_name='studentattendance',
            constraint=models.UniqueConstraint(fields=('student', 'attendance_date'), name='unique_student_attendance_per_day'),
        ),
        migrations.AddConstraint(
            model_name='trainingsession',
            constraint=models.UniqueConstraint(fields=('batch', 'session_date'), name='unique_batch_session_date'),
        ),
    ]
