# Generated by Django 5.2.10 on 2026-02-18 10:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_alter_assignstudent_student'),
        ('faculty', '0004_facultydailyreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='trainingsession',
            constraint=models.UniqueConstraint(fields=('batch', 'session_date'), name='unique_batch_session_date'),
        ),
    ]
