# Generated by Django 5.2.10 on 2026-02-12 23:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
        ('adminapp', '0009_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comment', models.TextField(blank=True)),
                ('submitted_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('certificate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='adminapp.certificate')),
            ],
        ),
    ]
