# Generated by Django 5.2.10 on 2026-02-04 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Selected', 'Selected'), ('Rejected', 'Rejected'), ('Shortlisted', 'Shortlisted'), ('Interview', 'Interview')], default='Applied', max_length=20),
        ),
    ]
