# Generated by Django 5.2.10 on 2026-02-12 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_alter_jobapplication_status'),
        ('adminapp', '0007_alter_assignstudent_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='adminapp.course'),
        ),
    ]
