# Generated by Django 5.2.10 on 2026-02-12 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_student_course'),
        ('adminapp', '0007_alter_assignstudent_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='adminapp.course'),
        ),
    ]
