# Generated by Django 5.2.10 on 2026-02-23 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0004_alter_student_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='course',
        ),
    ]
